# Generated by Django 2.2.7 on 2020-01-23 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 13, 5, 18, 27941)),
        ),
    ]
