# Generated by Django 2.2 on 2020-03-05 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200305_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 17, 26, 49, 116270)),
        ),
    ]
