# Generated by Django 2.2.7 on 2020-01-28 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200123_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 11, 18, 27, 507755)),
        ),
    ]
