# Generated by Django 2.2.7 on 2020-01-28 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200128_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 28, 11, 19, 1, 689157)),
        ),
    ]
