# Generated by Django 2.2.7 on 2020-02-13 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_auto_20200213_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 13, 14, 26, 58, 127764)),
        ),
    ]
