# Generated by Django 2.2.7 on 2020-02-17 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_auto_20200214_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 23, 1, 13, 375510)),
        ),
    ]
