# Generated by Django 2.2.7 on 2020-02-26 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0054_auto_20200225_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 26, 15, 56, 5, 146957)),
        ),
    ]
