# Generated by Django 2.2.7 on 2020-02-27 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0055_auto_20200226_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 14, 10, 26, 922341)),
        ),
    ]
