# Generated by Django 2.2 on 2020-02-29 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0068_auto_20200229_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 21, 31, 31, 233448)),
        ),
    ]
