# Generated by Django 2.2 on 2020-02-29 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0069_auto_20200229_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 21, 33, 36, 274864)),
        ),
    ]
