# Generated by Django 2.2 on 2020-02-29 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0070_auto_20200229_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationery',
            name='discount_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 21, 35, 6, 807518)),
        ),
    ]
