# Generated by Django 2.2 on 2020-02-29 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0071_auto_20200229_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 22, 4, 33, 68429)),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='item_img',
            field=models.ImageField(default='', upload_to='stationaries_images'),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
