# Generated by Django 2.2.7 on 2019-11-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_api', '0002_auto_20191121_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='stk',
            name='MerchantRequestID',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
