# Generated by Django 2.2.7 on 2020-02-27 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eLibrary', '0004_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_no', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('total_books_due', models.IntegerField(default=0)),
                ('pic', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
